### ISSUE TITLE
eleos on MAC does not synch, no nodes

### ISSUE THREAD

**Issue by richl1** [ZencashOfficial/eleos#13]
eleos on MAC does not synch, no nodes are found, synch is N/A

eleos behaves identically to the windows version if you do not add node to the zen.conf file.  For Windows, I saw a fix was to populate zen.conf with "addnode" lines see https://www.youtube.com/watch?v=bBFgOcyi-Lw  

Is there a similar fix for MAC OS?

**Comment by masterdubs** [comment]
https://steemit.com/eleos/@masterdubs/how-to-install-eleos-wallet-for-zencash-on-mac

**Comment by tarrenj** [comment]
As per [The Getting Started Guide](https://forum.zensystem.io/t/getting-started-faq/101/2), the zend.conf file is in `~/Library/Application Support/Zen/`.  Go ahead and add the nodes there, and then restart the wallet.

I'm going to close this now.
