### ISSUE TITLE
0.0.9 windows zip shows 0.0.7 in package.json 

### ISSUE THREAD

**Issue by ADumaine** [ZencashOfficial/eleos#15]
I just downloaded the zip for the hard fork, removed the files in the eleos folder and replaced with 0.0.9.

UI version still shows 0.0.7.  so does package.json.

Is this just a version issue or is this not ready for the hard fork?

**Comment by mattwkcc** [comment]
Also have this issue

**Comment by aayanl** [comment]
reuploaded with the correct version
