### ISSUE TITLE
question

### ISSUE THREAD

**Issue by inzejn** [ZencashOfficial/eleos#18]
WILL SOMEONE HELP ME TO GET MY WALLET SYNCED!? I HAVE MONEY THERE GUYS. WAITING FOR RESPONESE FOR 2 DAYS

**Comment by aayanl** [comment]
No need to scream, can you give info about the problem?

**Comment by inzejn** [comment]
I need to....

win 10 x64
0.0.7 currect version.
Version before was 0.0.5, synced and was working fine. I saved wallet.dat and chain data. Reinstalled to version 0.09, got stucked in syncing @98%, installed 0.0.7, got stucked @ 98

**Comment by inzejn** [comment]
I see adreses, but i cant see new transactions, new adresses and new balance.

**Comment by inzejn** [comment]
Current Balance: 0.00 zen  (Transparent: 0.00 zen/ Private: 0.00 zen)  | Connections: 8  | Sync Status: 98.1% !

**Comment by aayanl** [comment]
You need version 0.0.9

**Comment by aayanl** [comment]
Do windows+r and type in %APPDATA% go to the Zen folder and delete Blocks/ and Chainstate/. After that restart eleos and resync

**Comment by inzejn** [comment]
I done that already.

**Comment by inzejn** [comment]
And i used 0.0.9 version also

**Comment by inzejn** [comment]
0.0.7 stuck on 98.1% for loongg timeee

0.0.9 stuck on 98.9% for a long timee :(

**Comment by aayanl** [comment]
Have you deleted the blocks and chainstate folders in the Zen folder?

**Comment by inzejn** [comment]
Yeah, its like i done clean "install", just wallet.dat is old file

**Comment by inzejn** [comment]
I can just save wallet.dat and try to sync new wallet?

**Comment by inzejn** [comment]
And if new wallet got synced, i just replace wallet.dat, that could work or no ?

**Comment by aayanl** [comment]
You just need to delete the folder `blocks` and `chainstate` inside the Zen folder, no need to nuke everything

**Comment by inzejn** [comment]
Yeah, i figured out that my self, but that doesn't work for me. I done that, twice in last 2 days..im gonna do it again now, already started to sync, and will see will it change in next few hours, if not, i guess i need to say bye bye to my money

**Comment by inzejn** [comment]
It didnt worked on my pc so i tryed on another, there was fine, i have no idea why it didn't synced here, i reinstalled win and its 100% after reinstallation. P.S there were a lot of free space, so it wasn't space on hdd. Ty for response.

**Comment by aayanl** [comment]
awesome 👍
