### ISSUE TITLE
0.0.9 won't start

### ISSUE THREAD

**Issue by commie256** [ZencashOfficial/eleos#19]
Ends up with the message "check if daemon is already running". This started when I uninstalled 0.0.7 and downloaded 0.0.9. What should I do?

**Comment by aayanl** [comment]
Open Task manager can make sure `zend.exe` isn't there, if it is, kill it. Then start eleos

**Comment by commie256** [comment]
Tried that already, didn't help. Same message over and over again.

**Comment by Zephir014** [comment]
same issue for me

**Comment by commie256** [comment]
I've sorted it out by completely uninstalling Eleos (incl. all registry entries), deleting zen, zcl and zec folders in %appdata% ant then installing eleos from scratch and restoring wallets from backup.

**Comment by Zephir014** [comment]
Ok, thanks, just delete zen, zcl and eleos folders in %appdata% works for me :)
