### ISSUE TITLE
Error Start

### ISSUE THREAD

**Issue by lelbo** [ZencashOfficial/eleos#2]
hello,
i have windows 10

I delete app/zen  /zcashparameter

But i run 0.0.7 eleos, start error
My antivirus allert, but have blocked this.

![image](https://user-images.githubusercontent.com/20744731/27039643-c53c3fe8-4f8e-11e7-94e7-e4ecefb4aab8.png)

![image](https://user-images.githubusercontent.com/20744731/27039669-da4eb956-4f8e-11e7-85fb-c6b674fb2440.png)

**Comment by myk1984** [comment]
Hello!
I have a problem, like this!
Please Help

**Comment by needA-zenWallet** [comment]
It works for me,  you should have gotten at least 2 messages, one from windows firewall and one from your virus SW.  Eleos runs zend in the background, zend needs to be allowed by firewall and virus SW.  Try to wipe everything out and start fresh, delete in C:\Users\*****\AppData\Roaming\  the zen folder, ZcashParams folder and eleos folder.

**Comment by lelbo** [comment]
'' error downloading files ''

**Comment by rg1000** [comment]
this POS still doesn't work on windows 7 pro and windows 10 64. Why giving up on a working ZCL/ZEC wallet and change it to this piece of crap? Don't they teach in college that if ain't broke don't fix it? Why do you guys keep the DAO if you can't do shit? I followed all the steps outlined. It does download the proving keys, starts zend and can't communicate with it. Keeps starting new zend processes every few seconds. Give up on this POS and go back to what works, the zcl/zec wallet. We miners are paying you!!!!!
![capture](https://user-images.githubusercontent.com/19496539/27062525-789407e0-4fa0-11e7-8c40-823da9aa7283.JPG)
