### ISSUE TITLE
issue with Wallet daemon

### ISSUE THREAD

**Issue by madtomic** [ZencashOfficial/eleos#22]
![image](https://user-images.githubusercontent.com/6004542/29301817-f1330204-814c-11e7-9866-1f5d93440c70.png)

Any help would be great. Thanks

**Comment by madtomic** [comment]
fixed but wallet balance still not restored

**Comment by yasirw** [comment]
Hello,
How did you fix it? I am facing the same issue.

**Comment by tarrenj** [comment]
Eleos has been deprecated, try using swing wallet?
https://forum.zensystem.io/t/eleos-is-now-deprecated-please-use-other-clients-instead/447
