### ISSUE TITLE
Can not open my zcash wallet

### ISSUE THREAD

**Issue by goldflower** [ZencashOfficial/eleos#24]
It tried several times of

"initializing" -> "loading block index" -> "verifying blocks"

and give me 

<img width="419" alt="2017-11-01 11 01 33" src="https://user-images.githubusercontent.com/7734671/32258183-125f16f4-bef4-11e7-8b91-70d2b6ca7b1b.png">

The zen wallet was ok, what's the problem?

**Comment by LukasBures** [comment]
sorry Eleos is not supported, use another wallet
