### ISSUE TITLE
0.0.7 Zen bad sync

### ISSUE THREAD

**Issue by Clayman1979** [ZencashOfficial/eleos#4]
Everytime I start Zen wallet, it starts to sync anew from 76%.
Also, zend loading one of cores to maximum even when the wallet is idle.
I'm running windows 7 x64.

**Comment by LukasBures** [comment]
try to add nodes to config
more info here
https://forum.zensystem.io/t/the-official-eleos-support-thread/77

**Comment by Clayman1979** [comment]
This doesn't solve the problem.
It seems blocks past 76-78% are simply not saved on my disk (or deleted after exit).
