### ISSUE TITLE
restore wallet

### ISSUE THREAD

**Issue by lelbo** [ZencashOfficial/eleos#5]
i have upate Eleos, but i have this  and nno wallet 

![image](https://user-images.githubusercontent.com/20744731/27095526-519aeaa4-506e-11e7-84ce-257dbce6b327.png)

**Comment by devildog81** [comment]
Same problem here.

**Comment by lelbo** [comment]
all my zen 2 times erase

**Comment by LukasBures** [comment]
try to ask here

https://forum.zensystem.io/t/the-official-eleos-support-thread/77

you can import them manually.
