### ISSUE TITLE
Sync Status: NaN%Sync Status: NaN%

### ISSUE THREAD

**Issue by gonzalezea** [ZencashOfficial/eleos#7]
First time using eleos, after initial run & downloading sprout keys, nothing happened and status is always NAN%. After almost 2h waiting for some change, only see a lots of msgs (like below) in Roaming\Zen\debug.log

keypool reserve 3
keypool return 3

Windows 10 Pro x64
eleos v0.0.7

**Comment by LukasBures** [comment]
try to add nodes to config
more info here
https://forum.zensystem.io/t/the-official-eleos-support-thread/77

**Comment by aayanl** [comment]
fixed with new nodes
