### ISSUE TITLE
instructions clarifications

### ISSUE THREAD

**Issue by ITwrx** [ZencashOfficial/eleos#9]
i'm trying to install for GNU+Linox and i'm not understanding the eleos instructions. it makes sense to me until it says:

> Copy the Zclassic/Zcash wallet daemon into the elos directory (name the binary zcld-linux or zcashd-linux)

> cp ~/Builds/zclassic/src/zcashd ~/Builds/elos/zcld-linux

> or

> cp ~/Builds/zcash/src/zcashd ~/Builds/elos/zcashd-linux

what "Zclassic/Zcash wallet daemon"? (also, normally, command instructiions don't invent paths/directories that weren't created during previous steps of the instructions. i could assume and hunt, but i'd rather not.) Is there not a forked/zencash version of that daemon? is it not included with this wallet? Or does it come from https://github.com/ZencashOfficial/zen? do we have to have that zen client to run this wallet gui or under what circumstances do we need the "client" software? if it includes a cli only wallet that works properly and/or is more secure, then i'd rather not bother with this gui anyways (unless it's extra fancy like Parity). Anyway, that readme starts with 

> The easiest way to get started is to download one of the available graphical wallets from Zdeveloper.org

which links to "the wiki software time forgot" with windows and mac downloads... shooting pain in left arm...  :)

thanks

**Comment by jiri-novotny** [comment]
Hi, you can obtain zen wallet daemon here https://github.com/ZencashOfficial/zen/releases
After installation you should get zend and zen-cli which you can use with wallet

**Comment by ITwrx** [comment]
thanks! i'll check it out.
